/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.Traductor;
/**
 *
 * @author Liber
 */
public class TraductorVentana extends javax.swing.JInternalFrame {
    private String idioma;
    private int id_idioma;
    /**
     * Creates new form VentanaInicial
     * @param
     */
    /**
     * Creates new form TraductorVentana
     */
    public TraductorVentana() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucidoComplete21 = new org.edisoncor.gui.panel.PanelTranslucidoComplete2();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        btnIngles = new org.edisoncor.gui.button.ButtonRound();
        btnTraducir = new org.edisoncor.gui.button.ButtonRound();
        txtTraducir = new javax.swing.JTextField();
        btnKichwa = new org.edisoncor.gui.button.ButtonRound();
        btnEspañol = new org.edisoncor.gui.button.ButtonRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(" Traductor Ingles-Español-Kichwa");
        setVisible(true);

        panelTranslucidoComplete21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        panelTranslucidoComplete21.setForeground(new java.awt.Color(255, 255, 204));
        panelTranslucidoComplete21.setColorPrimario(new java.awt.Color(0, 255, 51));
        panelTranslucidoComplete21.setColorSecundario(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(204, 255, 204));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setCaretColor(new java.awt.Color(255, 204, 0));
        txtArea.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        txtArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtArea);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnIngles.setBackground(new java.awt.Color(153, 255, 0));
        btnIngles.setForeground(new java.awt.Color(0, 0, 0));
        btnIngles.setText("Ingles");
        btnIngles.setColorDeSombra(new java.awt.Color(0, 204, 0));
        btnIngles.setEnabled(false);
        btnIngles.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInglesActionPerformed(evt);
            }
        });

        btnTraducir.setBackground(new java.awt.Color(0, 255, 102));
        btnTraducir.setForeground(new java.awt.Color(0, 0, 0));
        btnTraducir.setText("Traducir");
        btnTraducir.setColorDeSombra(new java.awt.Color(0, 204, 0));
        btnTraducir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });

        txtTraducir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTraducir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTraducir.setToolTipText("Ingrese la palabra...");
        txtTraducir.setActionCommand("<Not Set>");
        txtTraducir.setEnabled(false);
        txtTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraducirActionPerformed(evt);
            }
        });

        btnKichwa.setBackground(new java.awt.Color(153, 255, 0));
        btnKichwa.setForeground(new java.awt.Color(0, 0, 0));
        btnKichwa.setText("Kichwa");
        btnKichwa.setColorDeSombra(new java.awt.Color(0, 204, 0));
        btnKichwa.setEnabled(false);
        btnKichwa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnKichwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKichwaActionPerformed(evt);
            }
        });

        btnEspañol.setBackground(new java.awt.Color(153, 255, 0));
        btnEspañol.setForeground(new java.awt.Color(0, 0, 0));
        btnEspañol.setText("Español");
        btnEspañol.setColorDeSombra(new java.awt.Color(0, 204, 0));
        btnEspañol.setEnabled(false);
        btnEspañol.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspañolActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese la palabra a traducir");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escoja el idioma");

        javax.swing.GroupLayout panelTranslucidoComplete21Layout = new javax.swing.GroupLayout(panelTranslucidoComplete21);
        panelTranslucidoComplete21.setLayout(panelTranslucidoComplete21Layout);
        panelTranslucidoComplete21Layout.setHorizontalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucidoComplete21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(btnEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(btnKichwa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                .addGroup(panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(btnTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(txtTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelTranslucidoComplete21Layout.setVerticalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKichwa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInglesActionPerformed

        idioma=btnIngles.getText();
        id_idioma=1;
        btnsIdiomas(idioma, id_idioma);
    }//GEN-LAST:event_btnInglesActionPerformed

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        // TODO add your handling code here:
        txtTraducir.setEnabled(true);
        btnEspañol.setEnabled(true);
        btnIngles.setEnabled(true);
        btnKichwa.setEnabled(true);
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void txtTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraducirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTraducirActionPerformed

    private void btnKichwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKichwaActionPerformed
        // TODO add your handling code here:
        idioma=btnKichwa.getText();
        id_idioma=2;
        btnsIdiomas(idioma, id_idioma);
    }//GEN-LAST:event_btnKichwaActionPerformed

    private void btnEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspañolActionPerformed
        // TODO add your handling code here:
        idioma=btnEspañol.getText();
        id_idioma=0;
        btnsIdiomas(idioma, id_idioma);
    }//GEN-LAST:event_btnEspañolActionPerformed

    private void txtAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtAreaAncestorAdded
        // TODO add your handling code here:
        txtArea.setText("""
                        Bienvenido a nuestro traductor de Español-Ingles-Kichwa:
                        -Para desbloquear el sistema, presione el boton 'Traducir'
                        -Luego coloque una palabra que quiera traducir
                        -Por ultimo seleccione el idioma de la palabra para que lo traduzca""");
    }//GEN-LAST:event_txtAreaAncestorAdded

    public void btnsIdiomas(String idioma, int id) {
        Traductor traductor = new Traductor();
        String palabra = txtTraducir.getText();
        palabra = traductor.eliminarTildes(palabra);
        if (txtTraducir.getText() != null && !"".equals(txtTraducir.getText().replaceAll(" ", ""))) {
            if (traductor.buscarIdPalabara(palabra, id_idioma)) {
                txtArea.setText(traductor.traducirPalabra(idioma, palabra, id_idioma));
                txtTraducir.setText("");
            } else {
                txtArea.setText("La palabra no es del mismo idioma \nColoque una palabra en el idioma escogido: " + idioma);
                txtTraducir.setText("");
            }
        } else {
            txtArea.setText("No hay ninguna palabra para ser traducida \nPorfavor coloque una palabra para ser traducida");
            txtTraducir.setText("");
        }
        
    }
    public JTextArea getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(JTextArea txtArea) {
        this.txtArea = txtArea;
    }

    public JTextField getTxtTraducir() {
        return txtTraducir;
    }

    public void setTxtTraducir(JTextField txtTraducir) {
        this.txtTraducir = txtTraducir;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnEspañol;
    private org.edisoncor.gui.button.ButtonRound btnIngles;
    private org.edisoncor.gui.button.ButtonRound btnKichwa;
    private org.edisoncor.gui.button.ButtonRound btnTraducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete2 panelTranslucidoComplete21;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtTraducir;
    // End of variables declaration//GEN-END:variables
}
