package modelo;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.HashMap;

public class Traductor {

    private final HashMap<String, ArrayList<String>> diccionario;

    public Traductor(HashMap<String, ArrayList<String>> diccionario) {

        this.diccionario = diccionario;
    }

    public Traductor() { // Contruimos la clase traductor
        diccionario = new HashMap<>();
        inicializarDiccionario();
    }

    public Traductor(HashMap<String, ArrayList<String>> diccionario, String idioma) {
        this.diccionario = diccionario;

    }

    private void inicializarDiccionario() { // Inicalizamos el diccionario con palabras en español y kichwa
        ArrayList<String> traducciones = new ArrayList<>();
        traducciones.add("hola");
        traducciones.add("hello");
        traducciones.add("imanalla");
        traducciones.add("adiós");
        traducciones.add("goodbye");
        traducciones.add("kayakama");
        traducciones.add("perro");
        traducciones.add("dog");
        traducciones.add("ashku");
        traducciones.add("gato");
        traducciones.add("cat");
        traducciones.add("mishi");
        traducciones.add("raton");
        traducciones.add("mouse");
        traducciones.add("ukucha");
        traducciones.add("toro");
        traducciones.add("bull");
        traducciones.add("wagra");
        traducciones.add("agua");
        traducciones.add("water");
        traducciones.add("yaku");
        traducciones.add("viento");
        traducciones.add("wind");
        traducciones.add("wayra");
        traducciones.add("buenos dias");
        traducciones.add("good morning");
        traducciones.add("alli punlla");
        traducciones.add("buenas tardes");
        traducciones.add("good afternoon");
        traducciones.add("alli Chishi");
        traducciones.add("piso");
        traducciones.add("floor");
        traducciones.add("pampa");
        traducciones.add("dia");
        traducciones.add("day");
        traducciones.add("punlla");
        traducciones.add("tarde");
        traducciones.add("evening");
        traducciones.add("chishi");
        traducciones.add("noche");
        traducciones.add("night");
        traducciones.add("tuta");
        traducciones.add("lana");
        traducciones.add("wool");
        traducciones.add("miklla");
        traducciones.add("quemar");
        traducciones.add("burn");
        traducciones.add("rupachiy");
        traducciones.add("fuego");
        traducciones.add("fire");
        traducciones.add("nina");
        traducciones.add("calentar");
        traducciones.add("heat");
        traducciones.add("kunuchiy");
        traducciones.add("caminar");
        traducciones.add("walk");
        traducciones.add("purik");
        traducciones.add("ver");
        traducciones.add("watch");
        traducciones.add("rikuy");
        traducciones.add("olvidar");
        traducciones.add("forget");
        traducciones.add("kungarina");
        traducciones.add("soñar");
        traducciones.add("dream");
        traducciones.add("muskuna");
        traducciones.add("yo");
        traducciones.add("i");
        traducciones.add("ñuka");
        traducciones.add("ustedes");
        traducciones.add("you");
        traducciones.add("kankuna");
        traducciones.add("teclado");
        traducciones.add("keyboard");
        traducciones.add("no existe esta palabra");
        traducciones.add("matrimonio");
        traducciones.add("marriage");
        traducciones.add("kallarana");
        traducciones.add("dulce");
        traducciones.add("sweet");
        traducciones.add("mishki");
        traducciones.add("sol");
        traducciones.add("sun");
        traducciones.add("inti");
        traducciones.add("luna");
        traducciones.add("moon");
        traducciones.add("killa");
        traducciones.add("vamonos");
        traducciones.add("let's go");
        traducciones.add("jaku");
        traducciones.add("venir");
        traducciones.add("come");
        traducciones.add("shamuy");
        traducciones.add("neblina");
        traducciones.add("fog");
        traducciones.add("puyo");
        traducciones.add("huevo");
        traducciones.add("egg");
        traducciones.add("ruro");
        traducciones.add("duro");
        traducciones.add("hard");
        traducciones.add("shinchy");
        traducciones.add("frio");
        traducciones.add("cold");
        traducciones.add("chiry");
        traducciones.add("caliente");
        traducciones.add("hot");
        traducciones.add("kunuy");
        traducciones.add("lodo");
        traducciones.add("sludge");
        traducciones.add("turu");
        traducciones.add("sapo");
        traducciones.add("joad");
        traducciones.add("jamp'atu");
        traducciones.add("lluvia");
        traducciones.add("rain");
        traducciones.add("tamia");
        traducciones.add("nevado");
        traducciones.add("snowy");
        traducciones.add("cazshka");
        traducciones.add("montańa");
        traducciones.add("mountain");
        traducciones.add("urku");
        traducciones.add("gallina");
        traducciones.add("hen");
        traducciones.add("guashpa");
        traducciones.add("pollo");
        traducciones.add("chicken");
        traducciones.add("chuchi");
        traducciones.add("caballo");
        traducciones.add("horse");
        traducciones.add("apyu");
        traducciones.add("zorro");
        traducciones.add("fox");
        traducciones.add("atuk");
        traducciones.add("leña");
        traducciones.add("firewood");
        traducciones.add("yanta");
        traducciones.add("luz");
        traducciones.add("ligth");
        traducciones.add("achik");
        traducciones.add("tejer");
        traducciones.add("weave");
        traducciones.add("awana");
        traducciones.add("guerra");
        traducciones.add("war");
        traducciones.add("makanakuy");
        traducciones.add("reloj");
        traducciones.add("clock");
        traducciones.add("pachachik");
        traducciones.add("escuela");
        traducciones.add("school");
        traducciones.add("yachana wasi");
        traducciones.add("libro");
        traducciones.add("book");
        traducciones.add("kamu");
        traducciones.add("pluma");
        traducciones.add("feather");
        traducciones.add("patpa");
        traducciones.add("comida");
        traducciones.add("food");
        traducciones.add("mikuna");
        traducciones.add("desayuno");
        traducciones.add("breakfast");
        traducciones.add("chinlli");
        traducciones.add("crudo");
        traducciones.add("raw");
        traducciones.add("chawa");
        traducciones.add("abrazo");
        traducciones.add("hug");
        traducciones.add("ukllarina");
        traducciones.add("abierto");
        traducciones.add("open");
        traducciones.add("paskana");
        traducciones.add("abuelo");
        traducciones.add("grandfather");
        traducciones.add("hatun yaya");
        traducciones.add("amarillo");
        traducciones.add("yellow");
        traducciones.add("killu");
        traducciones.add("amigo");
        traducciones.add("friend");
        traducciones.add("mashi");
        traducciones.add("amor");
        traducciones.add("love");
        traducciones.add("uyani");
        traducciones.add("animal");
        traducciones.add("animal");
        traducciones.add("sacha wiwa");
        traducciones.add("aprender");
        traducciones.add("learn");
        traducciones.add("yachakuna");
        traducciones.add("arbol");
        traducciones.add("tree");
        traducciones.add("yura");
        traducciones.add("arriba");
        traducciones.add("up");
        traducciones.add("hawa");
        traducciones.add("azul");
        traducciones.add("blue");
        traducciones.add("ankas");
        traducciones.add("gavilan");
        traducciones.add("hawk");
        traducciones.add("hanka");
        traducciones.add("hilo");
        traducciones.add("thread");
        traducciones.add("miqya");
        traducciones.add("bañar");
        traducciones.add("bathe");
        traducciones.add("armana");
        traducciones.add("decir");
        traducciones.add("say");
        traducciones.add("rimana");
        traducciones.add("bien");
        traducciones.add("well");
        traducciones.add("alli");
        traducciones.add("blanco");
        traducciones.add("white");
        traducciones.add("yurak");
        traducciones.add("boca");
        traducciones.add("mouth");
        traducciones.add("shimi");
        traducciones.add("brazo");
        traducciones.add("arm");
        traducciones.add("rikra");
        traducciones.add("blando");
        traducciones.add("soft");
        traducciones.add("apilla");
        traducciones.add("bobo");
        traducciones.add("fool");
        traducciones.add("upa");
        traducciones.add("bravo");
        traducciones.add("fierce");
        traducciones.add("piñak");
        traducciones.add("broma");
        traducciones.add("joke");
        traducciones.add("yankapukllay");
        traducciones.add("brujo");
        traducciones.add("wizard");
        traducciones.add("shaman");
        traducciones.add("bosque");
        traducciones.add("forest");
        traducciones.add("sacha");
        traducciones.add("burlarse");
        traducciones.add("mock");
        traducciones.add("asipayana");
        traducciones.add("cagar");
        traducciones.add("poop");
        traducciones.add("ismana");
        traducciones.add("caer");
        traducciones.add("fall");
        traducciones.add("urmana");
        traducciones.add("caja");
        traducciones.add("box");
        traducciones.add("purunku");
        traducciones.add("ano");
        traducciones.add("anus");
        traducciones.add("siki utuku");
        traducciones.add("teniente");
        traducciones.add("lieutenant");
        traducciones.add("kitilli apuk");
        traducciones.add("pene");
        traducciones.add("dick");
        traducciones.add("puma ullu");
        traducciones.add("primavera");
        traducciones.add("spring");
        traducciones.add("sisa");
        traducciones.add("reir");
        traducciones.add("laugh");
        traducciones.add("asina");
        traducciones.add("señorita");
        traducciones.add("miss");
        traducciones.add("kuytsa");
        traducciones.add("machete");
        traducciones.add("machete");
        traducciones.add("kutana");
        traducciones.add("macho");
        traducciones.add("male");
        traducciones.add("kari");
        traducciones.add("menstruacion");
        traducciones.add("menstruation");
        traducciones.add("warmi unkuy");
        traducciones.add("mesa");
        traducciones.add("table");
        traducciones.add("pataku");
        traducciones.add("sesos");
        traducciones.add("brains");
        traducciones.add("ñunktu");
        traducciones.add("sudor");
        traducciones.add("sweat");
        traducciones.add("jumpi");
        traducciones.add("testiculo");
        traducciones.add("testicle");
        traducciones.add("lulun");
        traducciones.add("tusa");
        traducciones.add("corncob");
        traducciones.add("kurunta");
        traducciones.add("trabajar");
        traducciones.add("work");
        traducciones.add("llamkana");
        traducciones.add("uva");
        traducciones.add("grape");
        traducciones.add("chiwilla");
        traducciones.add("vagina");
        traducciones.add("pussy");
        traducciones.add("raka");
        traducciones.add("trasero");
        traducciones.add("ass");
        traducciones.add("siki");
        traducciones.add("cerdo");
        traducciones.add("pig");
        traducciones.add("kuchi");
        traducciones.add("reír");
        traducciones.add("laugh");
        traducciones.add("asina");
        traducciones.add("acarrear");
        traducciones.add("carry");
        traducciones.add("astana");
        traducciones.add("canasta");
        traducciones.add("basket");
        traducciones.add("ashanka");
        traducciones.add("hediondo");
        traducciones.add("stinking");
        traducciones.add("ashnak");
        traducciones.add("lunes");
        traducciones.add("monday");
        traducciones.add("awaki");
        traducciones.add("fantasma");
        traducciones.add("ghost");
        traducciones.add("aya");
        traducciones.add("cementerio");
        traducciones.add("cemetery");
        traducciones.add("ayapampa");
        traducciones.add("esqueleto");
        traducciones.add("skeleton");
        traducciones.add("ayatullu");
        traducciones.add("carne");
        traducciones.add("meat");
        traducciones.add("aycha");
        traducciones.add("cazar");
        traducciones.add("hunt");
        traducciones.add("aychana");
        traducciones.add("luciernaga");
        traducciones.add("firefly");
        traducciones.add("aychañawi");
        traducciones.add("estafa");
        traducciones.add("fraud");
        traducciones.add("ayki");
        traducciones.add("comunidad");
        traducciones.add("community");
        traducciones.add("ayllullakta");
        traducciones.add("arma");
        traducciones.add("weapon");
        traducciones.add("ayñi");
        traducciones.add("mayo");
        traducciones.add("may");
        traducciones.add("aymuray");
        traducciones.add("puente");
        traducciones.add("bridge");
        traducciones.add("chaka");
        traducciones.add("escalera");
        traducciones.add("ladder");
        traducciones.add("chakana");
        traducciones.add("huella");
        traducciones.add("footprint");
        traducciones.add("chaki");
        traducciones.add("secar");
        traducciones.add("dry");
        traducciones.add("chakichina");
        traducciones.add("tobillo");
        traducciones.add("ankle");
        traducciones.add("chakimuku");
        traducciones.add("cultivo");
        traducciones.add("cultivation");
        traducciones.add("chakra");
        traducciones.add("insipido");
        traducciones.add("bland");
        traducciones.add("chamuk");
        traducciones.add("pierna");
        traducciones.add("leg");
        traducciones.add("chanka");
        traducciones.add("esperar");
        traducciones.add("wait");
        traducciones.add("chapana");
        traducciones.add("mensajero");
        traducciones.add("messenger");
        traducciones.add("chaski");
        traducciones.add("crudo");
        traducciones.add("raw");
        traducciones.add("chawa");
        traducciones.add("exprimir");
        traducciones.add("squeeze");
        traducciones.add("chawana");
        traducciones.add("sacudir");
        traducciones.add("shake");
        traducciones.add("chawsina");
        traducciones.add("asar");
        traducciones.add("roast");
        traducciones.add("chayana");
        traducciones.add("allí");
        traducciones.add("there");
        traducciones.add("chaypi");
        traducciones.add("todavia");
        traducciones.add("still");
        traducciones.add("chayra");
        traducciones.add("distinto");
        traducciones.add("different");
        traducciones.add("chikan");
        traducciones.add("perder");
        traducciones.add("lose");
        traducciones.add("chinkachina");
        traducciones.add("piña");
        traducciones.add("pineapple");
        traducciones.add("chiwilla");
        traducciones.add("seno");
        traducciones.add("breast");
        traducciones.add("chuchu");
        traducciones.add("impar");
        traducciones.add("odd");
        traducciones.add("chulla");
        traducciones.add("silencio");
        traducciones.add("silence");
        traducciones.add("chun");
        traducciones.add("tripa");
        traducciones.add("intestine");
        traducciones.add("chunchulli");
        traducciones.add("diez");
        traducciones.add("ten");
        traducciones.add("chunka");
        traducciones.add("rabo");
        traducciones.add("tail");
        traducciones.add("chupa");
        traducciones.add("colocar");
        traducciones.add("place");
        traducciones.add("churana");
        traducciones.add("hijo");
        traducciones.add("son");
        traducciones.add("churi");
        traducciones.add("caracol");
        traducciones.add("snail");
        traducciones.add("churu");
        traducciones.add("vacío");
        traducciones.add("empty");
        traducciones.add("chushak");
        traducciones.add("limpio");
        traducciones.add("clean");
        traducciones.add("chuya");
        traducciones.add("escopeta");
        traducciones.add("shotgun");
        traducciones.add("illapa");
        traducciones.add("maní");
        traducciones.add("peanut");
        traducciones.add("inchik");
        traducciones.add("zangano");
        traducciones.add("drone");
        traducciones.add("killa");
        traducciones.add("zapato");
        traducciones.add("shoe");
        traducciones.add("ushuta");
        traducciones.add("violar");
        traducciones.add("violate");
        traducciones.add("wakllichina");
        traducciones.add("viernes");
        traducciones.add("friday");
        traducciones.add("chaska");
        traducciones.add("vago");
        traducciones.add("lazy");
        traducciones.add("yanga puric");
        traducciones.add("verdadero");
        traducciones.add("true");
        traducciones.add("kikin");
        traducciones.add("universidad");
        traducciones.add("college");
        traducciones.add("yachana");
        traducciones.add("tio");
        traducciones.add("uncle");
        traducciones.add("jachi");
        traducciones.add("trampa");
        traducciones.add("trap");
        traducciones.add("tuklla");
        traducciones.add("terremoto");
        traducciones.add("earthquake");
        traducciones.add("allpa chukchuy");
        traducciones.add("ratero");
        traducciones.add("thief");
        traducciones.add("shuwa");
        traducciones.add("rabo");
        traducciones.add("tail");
        traducciones.add("chupa");
        traducciones.add("rayo");
        traducciones.add("thunder");
        traducciones.add("tulun");
        traducciones.add("rebelde");
        traducciones.add("rebellious");
        traducciones.add("mana uyak");
        traducciones.add("queso");
        traducciones.add("cheese");
        traducciones.add("makinchu");
        traducciones.add("oso");
        traducciones.add("bear");
        traducciones.add("ukumari");
        traducciones.add("nube");
        traducciones.add("cloud");
        traducciones.add("puyu");
        traducciones.add("mundo");
        traducciones.add("world");
        traducciones.add("pachamama");
        traducciones.add("moco");
        traducciones.add("booger");
        traducciones.add("kuña");
        traducciones.add("mamar");
        traducciones.add("suckle");
        traducciones.add("chuchuna");
        traducciones.add("loco");
        traducciones.add("crazy");
        traducciones.add("yuyayllak");
        traducciones.add("uno");
        traducciones.add("one");
        traducciones.add("shuk");
        traducciones.add("dos");
        traducciones.add("two");
        traducciones.add("ishkay");
        traducciones.add("tres");
        traducciones.add("three");
        traducciones.add("kimsa");
        traducciones.add("cuatro");
        traducciones.add("four");
        traducciones.add("chusku");
        traducciones.add("cinco");
        traducciones.add("five");
        traducciones.add("pichka");
        traducciones.add("seis");
        traducciones.add("six");
        traducciones.add("sukta");
        traducciones.add("siete");
        traducciones.add("seven");
        traducciones.add("kanchis");
        traducciones.add("ocho");
        traducciones.add("eight");
        traducciones.add("pusak");
        traducciones.add("nueve");
        traducciones.add("nine");
        traducciones.add("iskun");
        traducciones.add("once");
        traducciones.add("eleven");
        traducciones.add("chunka shuk");
        traducciones.add("doce");
        traducciones.add("twelve");
        traducciones.add("achik");
        traducciones.add("trece");
        traducciones.add("thirteen");
        traducciones.add("kimsa unga");
        traducciones.add("catorce");
        traducciones.add("fourteen");
        traducciones.add("chusku unga");
        traducciones.add("quince");
        traducciones.add("fifteen");
        traducciones.add("pichka unga");
        traducciones.add("dieciseis");
        traducciones.add("sixteen");
        traducciones.add("sukta unga");
        traducciones.add("diecisiete");
        traducciones.add("seventeen");
        traducciones.add("kanchis unga");
        traducciones.add("dieciocho");
        traducciones.add("eighteen");
        traducciones.add("pusak unga");
        traducciones.add("diecinueve");
        traducciones.add("nineteen");
        traducciones.add("iskun unga");
        traducciones.add("veinte");
        traducciones.add("twenty");
        traducciones.add("ishkay chunka");
        traducciones.add("veintiuno");
        traducciones.add("twenty one");
        traducciones.add("ishkay shunka shuk");
        traducciones.add("veintidos");
        traducciones.add("twenty two");
        traducciones.add("ishkay chunka ishkay");
        traducciones.add("treinta");
        traducciones.add("thirty");
        traducciones.add("kimsa chunka");
        traducciones.add("cuarenta");
        traducciones.add("fourty");
        traducciones.add("chusku chunka");
        traducciones.add("cincuenta");
        traducciones.add("fifty");
        traducciones.add("pichka chunka");
        traducciones.add("cien");
        traducciones.add("one hundred");
        traducciones.add("patsak");
        traducciones.add("doscientos");
        traducciones.add("two hundred");
        traducciones.add("ishkay patsak");
        traducciones.add("trescientos");
        traducciones.add("three hundred");
        traducciones.add("kimsa patsak");
        traducciones.add("mil");
        traducciones.add("one thousand");
        traducciones.add("waranka");
        traducciones.add("millon");
        traducciones.add("million");
        traducciones.add("hunu");
        traducciones.add("creer");
        traducciones.add("believe");
        traducciones.add("inina");
        traducciones.add("emperador");
        traducciones.add("emperor");
        traducciones.add("inka");
        traducciones.add("punto");
        traducciones.add("point");
        traducciones.add("iñu");
        traducciones.add("flaco");
        traducciones.add("thin");
        traducciones.add("irki");
        traducciones.add("excremento");
        traducciones.add("excrement");
        traducciones.add("isma");
        traducciones.add("podrido");
        traducciones.add("rotten");
        traducciones.add("ismu");
        traducciones.add("desgranar");
        traducciones.add("shell");
        traducciones.add("ishkuna");
        traducciones.add("orina");
        traducciones.add("urine");
        traducciones.add("ishpa");
        traducciones.add("vejiga");
        traducciones.add("bladder");
        traducciones.add("ishpapuru");
        traducciones.add("desnutrido");
        traducciones.add("undernourished");
        traducciones.add("itsi");
        traducciones.add("tio");
        traducciones.add("uncle");
        traducciones.add("jachi");
        traducciones.add("arriba");
        traducciones.add("up");
        traducciones.add("janak");
        traducciones.add("cojo");
        traducciones.add("lame");
        traducciones.add("janka");
        traducciones.add("medicamento");
        traducciones.add("medicine");
        traducciones.add("janpi");
        traducciones.add("curar");
        traducciones.add("cure");
        traducciones.add("janpina");
        traducciones.add("encender");
        traducciones.add("light");
        traducciones.add("japichina");
        traducciones.add("coger");
        traducciones.add("take");
        traducciones.add("japina");
        traducciones.add("atajar");
        traducciones.add("tackle");
        traducciones.add("jarkana");
        traducciones.add("corral");
        traducciones.add("pen");
        traducciones.add("jarkashka");
        traducciones.add("roncar");
        traducciones.add("snore");
        traducciones.add("jarnina");
        traducciones.add("grande");
        traducciones.add("big");
        traducciones.add("jatun");
        traducciones.add("manco");
        traducciones.add("one-armed");
        traducciones.add("chullamaki");
        traducciones.add("manosear");
        traducciones.add("grope");
        traducciones.add("llankana");
        traducciones.add("mar");
        traducciones.add("sea");
        traducciones.add("mamakucha");
        traducciones.add("marido");
        traducciones.add("husband");
        traducciones.add("kusa");
        traducciones.add("martes");
        traducciones.add("tuesday");
        traducciones.add("wamra");
        traducciones.add("marzo");
        traducciones.add("march");
        traducciones.add("pawkar");
        traducciones.add("masato");
        traducciones.add("masato");
        traducciones.add("pikak");
        traducciones.add("matar");
        traducciones.add("kill");
        traducciones.add("wañuchina");
        traducciones.add("menor");
        traducciones.add("younger");
        traducciones.add("kipa");
        traducciones.add("negro");
        traducciones.add("black");
        traducciones.add("yana");
        traducciones.add("nosotros");
        traducciones.add("our");
        traducciones.add("ñukanchik");
        traducciones.add("oler");
        traducciones.add("smell");
        traducciones.add("muktina");
        traducciones.add("oler mal");
        traducciones.add("smell bad");
        traducciones.add("asnal");
        traducciones.add("orina");
        traducciones.add("urine");
        traducciones.add("ishpa");
        traducciones.add("odiar");
        traducciones.add("hate");
        traducciones.add("chiknina");
        traducciones.add("oscuro");
        traducciones.add("dark");
        traducciones.add("amsa");
        traducciones.add("padre");
        traducciones.add("dad");
        traducciones.add("yaya");
        traducciones.add("panza");
        traducciones.add("puzun");
        traducciones.add("tanda");
        traducciones.add("patata");
        traducciones.add("potato");
        traducciones.add("papa");
        traducciones.add("pedo");
        traducciones.add("fart");
        traducciones.add("supi");
        traducciones.add("pezuña");
        traducciones.add("hoof");
        traducciones.add("sillu");
        traducciones.add("picante");
        traducciones.add("spicy");
        traducciones.add("jayak");
        traducciones.add("precio");
        traducciones.add("price");
        traducciones.add("chani");
        traducciones.add("pulga");
        traducciones.add("flea");
        traducciones.add("usa ipi");
        traducciones.add("pulgon");
        traducciones.add("plant louse");
        traducciones.add("pilis");
        traducciones.add("recto");
        traducciones.add("stright");
        traducciones.add("cusca");
        traducciones.add("secreto");
        traducciones.add("secret");
        traducciones.add("paka");
        traducciones.add("soplar");
        traducciones.add("blow");
        traducciones.add("pukuna");
        traducciones.add("tabaco");
        traducciones.add("tobacco");
        traducciones.add("shayri");
        traducciones.add("terraza");
        traducciones.add("terrace");
        traducciones.add("pata");
        traducciones.add("trompo");
        traducciones.add("spinning top");
        traducciones.add("kushpi");
        traducciones.add("ubicación");
        traducciones.add("location");
        traducciones.add("kuska");
        traducciones.add("ubre");
        traducciones.add("udder");
        traducciones.add("chuchu");
        traducciones.add("vacilar");
        traducciones.add("to make out");
        traducciones.add("aknina");
        traducciones.add("valiente");
        traducciones.add("brave");
        traducciones.add("sinchiruna");
        traducciones.add("veloz");
        traducciones.add("fast");
        traducciones.add("uktalla");
        traducciones.add("viajar");
        traducciones.add("travel");
        traducciones.add("purina");
        traducciones.add("viuda");
        traducciones.add("widow");
        traducciones.add("wakcha");
        traducciones.add("vomitar");
        traducciones.add("vomit");
        traducciones.add("kiwnana");
        traducciones.add("abuela");
        traducciones.add("grandmother");
        traducciones.add("jatun-mama");
        traducciones.add("mediano");
        traducciones.add("medium");
        traducciones.add("jatunnaya");
        traducciones.add("estornudar");
        traducciones.add("sneeze");
        traducciones.add("jatsiana");
        traducciones.add("alto");
        traducciones.add("tall");
        traducciones.add("jawa");
        traducciones.add("encima");
        traducciones.add("above");
        traducciones.add("jawaman");
        traducciones.add("sobre");
        traducciones.add("about");
        traducciones.add("jawapi");
        traducciones.add("subir");
        traducciones.add("go up");
        traducciones.add("jawayana");
        traducciones.add("pintar");
        traducciones.add("paint");
        traducciones.add("jawina");
        traducciones.add("pintarse");
        traducciones.add("Painted");
        traducciones.add("jawirina");
        traducciones.add("quemarse");
        traducciones.add("burn");
        traducciones.add("jawriyana");
        traducciones.add("bostezar");
        traducciones.add("yawn");
        traducciones.add("jawshana");
        traducciones.add("consuegro");
        traducciones.add("father-in-law");
        traducciones.add("jawya");
        traducciones.add("amargo");
        traducciones.add("bitter");
        traducciones.add("jayak");
        traducciones.add("pisar");
        traducciones.add("step");
        traducciones.add("jaytana");
        traducciones.add("tambalearse");
        traducciones.add("stagger");
        traducciones.add("jaytarina");
        traducciones.add("regar");
        traducciones.add("irrigate");
        traducciones.add("jichana");
        traducciones.add("abandonar");
        traducciones.add("abandon");
        traducciones.add("jichuca");
        traducciones.add("quedarse");
        traducciones.add("stay");
        traducciones.add("jichurina");
        traducciones.add("saltamontes");
        traducciones.add("grasshopper");
        traducciones.add("jiji");
        traducciones.add("arenilla");
        traducciones.add("grit");
        traducciones.add("jijiñas");
        traducciones.add("hierro");
        traducciones.add("iron");
        traducciones.add("jillay");
        traducciones.add("sesenta");
        traducciones.add("sixty");
        traducciones.add("sukta chunka");
        traducciones.add("setenta");
        traducciones.add("seventy");
        traducciones.add("kanchis chunka");
        traducciones.add("ochenta");
        traducciones.add("eighty");
        traducciones.add("pusak chunka");
        traducciones.add("noventa");
        traducciones.add("ninety");
        traducciones.add("iskun chunka");
        traducciones.add("cuatrocientos");
        traducciones.add("four hundred");
        traducciones.add("chusku patsak");
        traducciones.add("quinientos");
        traducciones.add("five hundred");
        traducciones.add("pichka patsak");
        traducciones.add("seiscientos");
        traducciones.add("six hundred");
        traducciones.add("sukta patsak");
        traducciones.add("setecientos");
        traducciones.add("seven hundred");
        traducciones.add("kanchis patsak");
        traducciones.add("ochocientos");
        traducciones.add("eight hundred");
        traducciones.add("pusak patsak");
        traducciones.add("novecientos");
        traducciones.add("nine hundred");
        traducciones.add("iskun patsak");
        traducciones.add("dos mil");
        traducciones.add("two hundred");
        traducciones.add("ishkay waranka");
        traducciones.add("morado");
        traducciones.add("purple");
        traducciones.add("maywa");
        traducciones.add("naranja");
        traducciones.add("orange");
        traducciones.add("chilina");
        traducciones.add("negro");
        traducciones.add("black");
        traducciones.add("yana");
        traducciones.add("rojo");
        traducciones.add("red");
        traducciones.add("puka");
        traducciones.add("verde");
        traducciones.add("green");
        traducciones.add("waylla");
        traducciones.add("cafe");
        traducciones.add("brown");
        traducciones.add("paku");
        traducciones.add("novia");
        traducciones.add("girlfriend");
        traducciones.add("sawarina warmi");
        traducciones.add("tortuga");
        traducciones.add("turtle");
        traducciones.add("yawati");
        traducciones.add("carro");
        traducciones.add("car");
        traducciones.add("antawa");
        traducciones.add("moto");
        traducciones.add("motorcycle");
        traducciones.add("kurun anta");
        traducciones.add("semen");
        traducciones.add("semen");
        traducciones.add("yuma");
        traducciones.add("tula");
        traducciones.add("tula");
        traducciones.add("loma");
        traducciones.add("puerta");
        traducciones.add("door");
        traducciones.add("punko");
        traducciones.add("goloso");
        traducciones.add("greedy");
        traducciones.add("jilluk");
        traducciones.add("pujar");
        traducciones.add("bid");
        traducciones.add("jipana");
        traducciones.add("feo");
        traducciones.add("ugly");
        traducciones.add("jirus");
        traducciones.add("culpa");
        traducciones.add("fault");
        traducciones.add("jucha");
        traducciones.add("inculpar");
        traducciones.add("blame");
        traducciones.add("juchachina");
        traducciones.add("pecar");
        traducciones.add("sin");
        traducciones.add("juchallina");
        traducciones.add("tentacion");
        traducciones.add("temptation");
        traducciones.add("juchanayay");
        traducciones.add("pecador");
        traducciones.add("sinner");
        traducciones.add("juchasapa");
        traducciones.add("silbar");
        traducciones.add("whistle");
        traducciones.add("jukipuna");
        traducciones.add("mojado");
        traducciones.add("wet");
        traducciones.add("juku");
        traducciones.add("sudor");
        traducciones.add("sweat");
        traducciones.add("jumpi");
        traducciones.add("sudar");
        traducciones.add("sweat");
        traducciones.add("jumpina");
        traducciones.add("acalorarse");
        traducciones.add("get hot");
        traducciones.add("jumpirina");
        traducciones.add("lleno");
        traducciones.add("full");
        traducciones.add("junta");
        traducciones.add("llenarse");
        traducciones.add("fill");
        traducciones.add("juntarina");
        traducciones.add("replicar");
        traducciones.add("retort");
        traducciones.add("juruna");
        traducciones.add("alerta");
        traducciones.add("alert");
        traducciones.add("jushujushu");
        traducciones.add("hueco");
        traducciones.add("hollow");
        traducciones.add("jutku");
        traducciones.add("perforarse");
        traducciones.add("Drilled");
        traducciones.add("jutkurina");
        traducciones.add("mandar");
        traducciones.add("send");
        traducciones.add("kachana");
        traducciones.add("soltar");
        traducciones.add("release");
        traducciones.add("kacharina");
        traducciones.add("sal");
        traducciones.add("salt");
        traducciones.add("kachi");
        traducciones.add("nuera");
        traducciones.add("daughter-in-law");
        traducciones.add("kachun");
        traducciones.add("roca");
        traducciones.add("rock");
        traducciones.add("kaka");
        traducciones.add("petrificarse");
        traducciones.add("petrify");
        traducciones.add("kakayana");
        traducciones.add("sobar");
        traducciones.add("knead");
        traducciones.add("kakuna");
        traducciones.add("hongo");
        traducciones.add("fungus");
        traducciones.add("kallampa");
        traducciones.add("principio");
        traducciones.add("beginning");
        traducciones.add("kallari");
        traducciones.add("expulsar");
        traducciones.add("throw out");
        traducciones.add("kallapachichina");
        traducciones.add("ahuyentar");
        traducciones.add("drive away");
        traducciones.add("kallpachina");
        traducciones.add("correr");
        traducciones.add("run");
        traducciones.add("kallpana");
        traducciones.add("lengua");
        traducciones.add("language");
        traducciones.add("kallu");
        traducciones.add("hablador");
        traducciones.add("talkative");
        traducciones.add("kallusapa");
        traducciones.add("aconsejar");
        traducciones.add("advise");
        traducciones.add("kamachina");
        traducciones.add("probar");
        traducciones.add("taste");
        traducciones.add("kamana");
        traducciones.add("regalo");
        traducciones.add("present");
        traducciones.add("kamari");
        traducciones.add("tostar");
        traducciones.add("toast");
        traducciones.add("kamchana");
        traducciones.add("criticar");
        traducciones.add("criticize");
        traducciones.add("kamina");
        traducciones.add("tu");
        traducciones.add("your");
        traducciones.add("kan");
        traducciones.add("exterior");
        traducciones.add("outside");
        traducciones.add("kanchaman");
        traducciones.add("morder");
        traducciones.add("bite");
        traducciones.add("kanina");
        traducciones.add("remorderse");
        traducciones.add("o prick");
        traducciones.add("kanirina");
        traducciones.add("coxis");
        traducciones.add("coccyx");
        traducciones.add("kanki tullu");
        traducciones.add("cacao");
        traducciones.add("cocoa");
        traducciones.add("kanpik");
        traducciones.add("grito");
        traducciones.add("shout");
        traducciones.add("kapari");
        traducciones.add("ordeñar");
        traducciones.add("milk");
        traducciones.add("kapina");
        traducciones.add("piel");
        traducciones.add("skin");
        traducciones.add("kara");
        traducciones.add("herida");
        traducciones.add("wound");
        traducciones.add("karacha");
        traducciones.add("vaina");
        traducciones.add("pod");
        traducciones.add("karan");
        traducciones.add("varón");
        traducciones.add("man");
        traducciones.add("kari");
        traducciones.add("soltera");
        traducciones.add("single woman");
        traducciones.add("kari-illak");
        traducciones.add("casada");
        traducciones.add("married");
        traducciones.add("kariyuk");
        traducciones.add("ensuciarse");
        traducciones.add("dirty");
        traducciones.add("karkayana");
        traducciones.add("lejos");
        traducciones.add("dirty");
        traducciones.add("karu");
        traducciones.add("distante");
        traducciones.add("distant");
        traducciones.add("karuman");
        traducciones.add("pacífico");
        traducciones.add("pacific");
        traducciones.add("kasi");
        traducciones.add("endurecido");
        traducciones.add("hardened");
        traducciones.add("kaspin");
        traducciones.add("espina");
        traducciones.add("thorn");
        traducciones.add("kasha");
        traducciones.add("cobija");
        traducciones.add("blanket");
        traducciones.add("katana");
        traducciones.add("remedar");
        traducciones.add("net fish");
        traducciones.add("katichina");
        traducciones.add("vender");
        traducciones.add("sell");
        traducciones.add("katuna");
        traducciones.add("torcer");
        traducciones.add("twist");
        traducciones.add("kawchuna");
        traducciones.add("cama");
        traducciones.add("bed");
        traducciones.add("kawitu");
        traducciones.add("crocante");
        traducciones.add("crispy");
        traducciones.add("kawlla");
        traducciones.add("torcer");
        traducciones.add("twist");
        traducciones.add("kawpuna");
        traducciones.add("revivir");
        traducciones.add("revive");
        traducciones.add("kawsachina");
        traducciones.add("vivir");
        traducciones.add("live");
        traducciones.add("kawsana");
        traducciones.add("resucitar");
        traducciones.add("resurrect");
        traducciones.add("kawsarina");
        traducciones.add("labio");
        traducciones.add("lip");
        traducciones.add("shimi");
        traducciones.add("ladera");
        traducciones.add("slope");
        traducciones.add("kinkray");
        traducciones.add("lampara");
        traducciones.add("lamp");
        traducciones.add("tuta sindina");
        traducciones.add("lamer");
        traducciones.add("lick");
        traducciones.add("llawkana");
        traducciones.add("leer");
        traducciones.add("read");
        traducciones.add("liina");
        traducciones.add("lengua");
        traducciones.add("tongue");
        traducciones.add("kallu");
        traducciones.add("leña");
        traducciones.add("wood");
        traducciones.add("yanta");
        traducciones.add("lento");
        traducciones.add("slow");
        traducciones.add("alli");
        traducciones.add("lepra");
        traducciones.add("leprosy");
        traducciones.add("caracha");
        traducciones.add("ley");
        traducciones.add("law");
        traducciones.add("kamachikushka shimi");
        traducciones.add("libre");
        traducciones.add("free");
        traducciones.add("chusak");
        traducciones.add("licor");
        traducciones.add("liqueur");
        traducciones.add("tiyawlla");
        traducciones.add("lima");
        traducciones.add("lime");
        traducciones.add("pimi");
        traducciones.add("llorar");
        traducciones.add("cry");
        traducciones.add("wakana");
        traducciones.add("lluvia");
        traducciones.add("rain");
        traducciones.add("tamya");
        traducciones.add("mascar");
        traducciones.add("chew");
        traducciones.add("mukuna");
        traducciones.add("montar");
        traducciones.add("ride");
        traducciones.add("sikana");
        traducciones.add("murcielago");
        traducciones.add("bat");
        traducciones.add("mashu");
        traducciones.add("muro");
        traducciones.add("wall");
        traducciones.add("sinchi");
        traducciones.add("noche");
        traducciones.add("night");
        traducciones.add("tuta");
        traducciones.add("niño");
        traducciones.add("kid");
        traducciones.add("wawa");
        traducciones.add("nutrir");
        traducciones.add("nourish");
        traducciones.add("karana");
        traducciones.add("obedecer");
        traducciones.add("obey");
        traducciones.add("uyana");
        traducciones.add("ortiga");
        traducciones.add("nettle");
        traducciones.add("chini");
        traducciones.add("pareja");
        traducciones.add("couple");
        traducciones.add("ishkanti");
        traducciones.add("parir");
        traducciones.add("give birth");
        traducciones.add("wachana");
        traducciones.add("parroquia");
        traducciones.add("parish church");
        traducciones.add("hatunkawsay");
        traducciones.add("partera");
        traducciones.add("midwife");
        traducciones.add("wachachik");
        traducciones.add("pato");
        traducciones.add("duck");
        traducciones.add("kulta");
        traducciones.add("pecho");
        traducciones.add("chest");
        traducciones.add("kasku");
        traducciones.add("poco");
        traducciones.add("a little bit");
        traducciones.add("ansa");
        traducciones.add("quemar");
        traducciones.add("burn");
        traducciones.add("rupana");
        traducciones.add("resucitar");
        traducciones.add("rise from the dead");
        traducciones.add("kawsarina");
        traducciones.add("resumen");
        traducciones.add("summary");
        traducciones.add("yuyaykunata");
        traducciones.add("roca");
        traducciones.add("rock");
        traducciones.add("rumi allpa");
        traducciones.add("romper");
        traducciones.add("broken");
        traducciones.add("pakina");
        traducciones.add("ropa interior");
        traducciones.add("underwear");
        traducciones.add("uku churarina");
        traducciones.add("salud");
        traducciones.add("health");
        traducciones.add("allikay");
        traducciones.add("sandalia");
        traducciones.add("sandal");
        traducciones.add("ushuta");
        traducciones.add("sangre");
        traducciones.add("blood");
        traducciones.add("yawar");
        traducciones.add("silla");
        traducciones.add("chair");
        traducciones.add("tyarina");
        traducciones.add("suciedad");
        traducciones.add("dirty");
        traducciones.add("tillka");
        traducciones.add("veneno");
        traducciones.add("poision");
        traducciones.add("wañuchik jampi");
        traducciones.add("venta");
        traducciones.add("sale");
        traducciones.add("katuna");
        traducciones.add("ventana");
        traducciones.add("window");
        traducciones.add("uchilla punku");
        traducciones.add("ventilador");
        traducciones.add("fan");
        traducciones.add("wayrachikuk");
        traducciones.add("venus");
        traducciones.add("goddess");
        traducciones.add("pakari kuyllur");
        traducciones.add("verbo");
        traducciones.add("verb");
        traducciones.add("imachik");
        traducciones.add("vesicula biliar");
        traducciones.add("biliary vesicular");
        traducciones.add("jayak");
        traducciones.add("volar");
        traducciones.add("fly");
        traducciones.add("pawana");
        traducciones.add("volcan");
        traducciones.add("vulcan");
        traducciones.add("urku");
        traducciones.add("voluntad");
        traducciones.add("will");
        traducciones.add("munay");
        traducciones.add("voz");
        traducciones.add("voice");
        traducciones.add("uyachi");
        traducciones.add("ya");
        traducciones.add("yeah");
        traducciones.add("ña");
        traducciones.add("yerno");
        traducciones.add("son in law");
        traducciones.add("masha");
        traducciones.add("yuca");
        traducciones.add("cassava");
        traducciones.add("lumu");
        traducciones.add("semaforo");
        traducciones.add("traffic light");
        traducciones.add("unancha");
        traducciones.add("playa");
        traducciones.add("beach");
        traducciones.add("tiyu allpa");
        traducciones.add("pluma");
        traducciones.add("feather");
        traducciones.add("willma");
        traducciones.add("poblacion");
        traducciones.add("population");
        traducciones.add("runallakta");
        traducciones.add("pobre");
        traducciones.add("poor");
        traducciones.add("tsuntsu wakcha");
        traducciones.add("piraña");
        traducciones.add("piranha");
        traducciones.add("paña");
        traducciones.add("palanca");
        traducciones.add("lever");
        traducciones.add("wanka");
        traducciones.add("nieto");
        traducciones.add("grandson");
        traducciones.add("churipak");
        traducciones.add("malvado");
        traducciones.add("evil");
        traducciones.add("millai");
        traducciones.add("mandon");
        traducciones.add("bossy");
        traducciones.add("apuyashka");
        traducciones.add("meter");
        traducciones.add("put");
        traducciones.add("satina");
        traducciones.add("miel");
        traducciones.add("honey");
        traducciones.add("huiru");
        traducciones.add("basura");
        traducciones.add("trash");
        traducciones.add("kupa");
        traducciones.add("medicina");
        traducciones.add("medicine");
        traducciones.add("hampi");
        traducciones.add("sitio");
        traducciones.add("place");
        traducciones.add("kaypi");
        traducciones.add("estrecho");
        traducciones.add("narrow");
        traducciones.add("kichki");
        traducciones.add("apretar");
        traducciones.add("squeeze");
        traducciones.add("kichkiyachina");
        traducciones.add("arrebatar");
        traducciones.add("snatch");
        traducciones.add("kichuna");
        traducciones.add("verdadero");
        traducciones.add("true");
        traducciones.add("kikin");
        traducciones.add("molestar");
        traducciones.add("bother");
        traducciones.add("killachina");
        traducciones.add("letra");
        traducciones.add("letter");
        traducciones.add("killka");
        traducciones.add("leer");
        traducciones.add("read");
        traducciones.add("killkakatina");
        traducciones.add("escribir");
        traducciones.add("to write");
        traducciones.add("killkana");
        traducciones.add("papel");
        traducciones.add("paper");
        traducciones.add("killkapanka");
        traducciones.add("hollín");
        traducciones.add("soot");
        traducciones.add("killmisha");
        traducciones.add("tapar");
        traducciones.add("cover");
        traducciones.add("killpana");
        traducciones.add("arrimar");
        traducciones.add("lean");
        traducciones.add("kimina");
        traducciones.add("picaflor");
        traducciones.add("hummingbird");
        traducciones.add("kinti");
        traducciones.add("quinua");
        traducciones.add("quinoa");
        traducciones.add("kinwa");
        traducciones.add("bulto");
        traducciones.add("bulk");
        traducciones.add("kipi");
        traducciones.add("diente");
        traducciones.add("tooth");
        traducciones.add("kiru");
        traducciones.add("salvarse");
        traducciones.add("escape");
        traducciones.add("kishpina");
        traducciones.add("cantón");
        traducciones.add("canton");
        traducciones.add("kiti");
        traducciones.add("conejo");
        traducciones.add("rabbit");
        traducciones.add("kunu");
        traducciones.add("calentar");
        traducciones.add("heat");
        traducciones.add("kunuchina");
        traducciones.add("espeso");
        traducciones.add("thick");
        traducciones.add("lapa");
        traducciones.add("hermanastra");
        traducciones.add("stepsister");
        traducciones.add("lapani");
        traducciones.add("sitio");
        traducciones.add("estomago");
        traducciones.add("stomach");
        traducciones.add("puzun");
        traducciones.add("ombligo");
        traducciones.add("belly button");
        traducciones.add("pupu");
        traducciones.add("aguacate");
        traducciones.add("avocado");
        traducciones.add("palta");
        traducciones.add("uña");
        traducciones.add("fingernail");
        traducciones.add("shizu");
        traducciones.add("televisor");
        traducciones.add("tv");
        traducciones.add("yawirkarikuy");
        traducciones.add("húmedo");
        traducciones.add("wet");
        traducciones.add("latsa");
        traducciones.add("ardor");
        traducciones.add("ardour");
        traducciones.add("lawrana");
        traducciones.add("clase");
        traducciones.add("class");
        traducciones.add("laya");
        traducciones.add("padrastro");
        traducciones.add("stepfather");
        traducciones.add("layaya");
        traducciones.add("huevo");
        traducciones.add("egg");
        traducciones.add("lulun");
        traducciones.add("yuca");
        traducciones.add("manioc");
        traducciones.add("lumu");
        traducciones.add("manglar");
        traducciones.add("mangrove");
        traducciones.add("lunchik");
        traducciones.add("pintado");
        traducciones.add("painted");
        traducciones.add("luyuluyu");
        traducciones.add("ofender");
        traducciones.add("offend");
        traducciones.add("llakichina");
        traducciones.add("apenado");
        traducciones.add("embarrassed");
        traducciones.add("llakilla");
        traducciones.add("pena");
        traducciones.add("sorrow");
        traducciones.add("llakimanta");
        traducciones.add("amar");
        traducciones.add("love");
        traducciones.add("llakina");
        traducciones.add("afligirse");
        traducciones.add("grieve");
        traducciones.add("llakirina");
        traducciones.add("ladrar");
        traducciones.add("bark");
        traducciones.add("llakllana");
        traducciones.add("pueblo");
        traducciones.add("village");
        traducciones.add("llakta");
        traducciones.add("poblador");
        traducciones.add("settler");
        traducciones.add("llaktayuk");
        traducciones.add("liso");
        traducciones.add("smooth");
        traducciones.add("llampu");
        traducciones.add("pulir");
        traducciones.add("polish");
        traducciones.add("llampuna");
        traducciones.add("pesado");
        traducciones.add("heavy");
        traducciones.add("llashak");
        traducciones.add("estrujar");
        traducciones.add("squeeze");
        traducciones.add("llapina");
        traducciones.add("aplastar");
        traducciones.add("crush");
        traducciones.add("llapichina");
        traducciones.add("sombra");
        traducciones.add("shadow");
        traducciones.add("llantuyana");
        traducciones.add("tocar");
        traducciones.add("touch");
        traducciones.add("llankana");
        traducciones.add("desnudo");
        traducciones.add("naked");
        traducciones.add("llatakara");
        traducciones.add("saliva");
        traducciones.add("saliva");
        traducciones.add("llawsa");
        traducciones.add("corona");
        traducciones.add("crown");
        traducciones.add("llawtu");
        traducciones.add("brillante");
        traducciones.add("bright");
        traducciones.add("llimpik");
        

      
        
        diccionario.put("palabras", traducciones); // Traduce la palabra
    }

    public boolean buscarIdPalabara(String palabra, int idPalabra) {
        ArrayList<String> traducciones = diccionario.get("palabras");
        int indicePalabra = traducciones.indexOf(palabra.toLowerCase());
        for (int i = idPalabra; i <= indicePalabra; i += 3) {
            
            if (indicePalabra == i) {
                return true;
            }
        }
        return indicePalabra == -1;

    }

    public String traducirPalabra(String idioma, String palabra, int id_idioma) { // obtiene la lista de traducciones
        ArrayList<String> traducciones = diccionario.get("palabras");
        int indicePalabra = traducciones.indexOf(palabra.toLowerCase());

        if (id_idioma == 0 && indicePalabra != -1) {

            return "Su traduccion para la palabra '" + palabra + "' en ingles es: "
                    + traducciones.get(indicePalabra + 1) + "\nSu traduccion para la palabra '" + palabra
                    + "' en kichwa es: " + traducciones.get(indicePalabra + 2);
        } else if (id_idioma == 1 && indicePalabra != -1) {
            return "Su traduccion para la palabra '" + palabra + "' en español es: "
                    + traducciones.get(indicePalabra - 1) + "\nSu traduccion para la palabra '" + palabra
                    + "' en kichwa es: " + traducciones.get(indicePalabra + 1);
        } else if (id_idioma == 2 && indicePalabra != -1) {
            return "Su traduccion para la palabra '" + palabra + "' en español es: "
                    + traducciones.get(indicePalabra - 2) + "\nSu traduccion para la palabra '" + palabra
                    + "' en ingles es: " + traducciones.get(indicePalabra - 1);
        } else {
            return "Traducción no encontrada para la palabra: " + palabra;
        }

    }

    public String eliminarTildes(String cadena) {
        String cadenaNormalizada = Normalizer.normalize(cadena, Normalizer.Form.NFD);
        return cadenaNormalizada.replaceAll("[^\\p{ASCII}]", "");
    }


}
